spring:
  application:
    name: RestaurantService
  zipkin:
    base-url: http://localhost:9998 #zipkin服务器地址
  sleuth:
    sampler:
      percentage: 1 #采样率
      
server:
  port: 8081 # 端口
  session-timeout: 60 # session超时
  error:
    path: /error #错误路径


#注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/