server:
  port: 9091
  
spring:
  application:
    name: HystrixServiceMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: 123456
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

    