server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    
security:
  basic:
    enabled: true
  user:
    name: test
    password: 123456