spring:
  application:
    name: UserService
    
server:
  port: 8082
  # context-path: /UserService

  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
