myauth:
  eureka:
    username: test
    password: 123456
    
server:
  port: 1113

spring:
  application:
    name: service-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://${myauth.eureka.username}:${myauth.eureka.password}@localhost:1111/eureka/
