spring:
  application:
    name: zipkinservice
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: 123456
    
server:
  port: 9998
  
eureka:
  client:
    serviceUrl:
      defalutZone: http://localhost:8761/eureka/