server:
  port: 9092

management:
  port: 9093
   
spring:
  application:
    name: TurbineService
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
turbine:
  app-config: HYSTRIXSERVICE,HYSTRIXSERVICE2  # 配置Eureka中的serviceId列表，表明监控哪些服务  
  cluster-name-expression: new String('default')
  combine-host-port: true #可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以host来区分不同的服务，这会使得在本地调试的时候，本机上的不同服务聚合成一个服务来统计。  
    