spring:
  application:
    name: ApiService

server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defalutZone: http://localhost:8761/eureka/
      
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000