spring:
  application:
    name: zipkinservice
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: 123456
  sleuth:
    enabled: false
  datasource:
    schema: classpath:/zipkin.sql
    url: jdbc:mysql://localhost:3306/zipkin
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    continue-on-error: true
    
server:
  port: 9998
  
eureka:
  client:
    serviceUrl:
      defalutZone: http://localhost:8761/eureka/

zipkin:
  storage:
    type: mysql
