myauth:
  eureka:
    username: test
    password: 123456
    
server:
  port: 2222
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kongdou/configs
          searchPaths: test/config-repo
          username: zhao.xiao.jie@outlook.com
          password: xiaojie@839
eureka:
  client:
    serviceUrl:
      defaultZone: http://${myauth.eureka.username}:${myauth.eureka.password}@localhost:8761/eureka/