myauth:
  eureka:
    username: test
    password: 123456
    
server:
  port: 2222
  
spring:
  application:
    name: config-server
  profiles:
    active: subversion
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: 123456
  cloud:
    config:
      server:
        #git:
          #uri: http://10.10.68.154:8088/configs
          #searchPaths: test/config-repo
          #username: *************
          #password: *************
        svn:
          uri: http://10.10.68.154:8088/svn/cloudconfig
          default-label: config
          searchPaths: config
          username: zhaoxiaojie
          password: zhaoxiaojie
          basedir: c:/config
eureka:
  client:
    serviceUrl:
      defaultZone: http://${myauth.eureka.username}:${myauth.eureka.password}@localhost:8761/eureka/
      
management:
  security:
    enabled: false